-- FP5 Cardio v12
-- Source of truth: Supabase. Original FileMaker values are immutable in raw_data.
-- Do NOT place the Supabase service-role key in GitHub.

create table if not exists public.fp5_patients (
  patient_id text primary key,
  nhc text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_fp5_patients_nhc on public.fp5_patients(nhc);
create index if not exists idx_fp5_patients_name on public.fp5_patients(display_name);

create table if not exists public.fp5_episodes (
  episode_id text primary key,
  patient_id text not null references public.fp5_patients(patient_id) on delete cascade,
  source_row integer not null,
  raw_data jsonb not null default '{}'::jsonb,
  validated_data jsonb not null default '{}'::jsonb,
  field_status jsonb not null default '{}'::jsonb,
  imported_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by text not null default 'web',
  unique(source_row)
);

create index if not exists idx_fp5_episodes_patient on public.fp5_episodes(patient_id);
create index if not exists idx_fp5_episodes_source_row on public.fp5_episodes(source_row);

create table if not exists public.fp5_field_definitions (
  field text primary key,
  label text not null,
  field_order integer not null,
  filemaker_type text,
  effective_type text,
  length integer,
  decimals integer,
  category text,
  data_kind text,
  allow_ai boolean not null default false,
  zero_policy text,
  missing_blank text not null default 'missing_no_revisado',
  missing_555 text not null default 'missing_revisado',
  review_status text,
  notes text,
  updated_at timestamptz not null default now()
);


alter table public.fp5_field_definitions add column if not exists effective_type text;

create table if not exists public.fp5_ai_extractions (
  id bigint generated by default as identity primary key,
  episode_id text not null references public.fp5_episodes(episode_id) on delete cascade,
  field text not null references public.fp5_field_definitions(field) on delete restrict,
  proposed_value jsonb,
  evidence text,
  confidence numeric(5,4),
  model text,
  status text not null default 'pending'
    check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by text
);

create index if not exists idx_fp5_ai_episode_status on public.fp5_ai_extractions(episode_id, status);

create table if not exists public.fp5_audit_log (
  id bigint generated by default as identity primary key,
  episode_id text not null references public.fp5_episodes(episode_id) on delete cascade,
  patient_id text,
  action text not null,
  field text,
  old_value jsonb,
  new_value jsonb,
  snapshot jsonb,
  source text not null default 'manual',
  changed_at timestamptz not null default now(),
  changed_by text not null default 'web'
);

create index if not exists idx_fp5_audit_episode on public.fp5_audit_log(episode_id, changed_at desc);

create table if not exists public.fp5_import_runs (
  id bigint generated by default as identity primary key,
  file_name text,
  file_sha256 text,
  source_rows integer,
  inserted_patients integer,
  inserted_episodes integer,
  status text not null default 'started',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  started_by text not null default 'web',
  notes text
);

alter table public.fp5_patients enable row level security;
alter table public.fp5_episodes enable row level security;
alter table public.fp5_field_definitions enable row level security;
alter table public.fp5_ai_extractions enable row level security;
alter table public.fp5_audit_log enable row level security;
alter table public.fp5_import_runs enable row level security;

-- Intentionally no anon/public policies. The Streamlit server uses the service-role key.
